# French verb conjugation data
# 100 most useful verbs for daily conversation

PRONOUNS = ["je", "tu", "il/elle", "on", "nous", "vous", "ils/elles"]

TENSES = {
    "présent": "Présent",
    "passé_composé": "Passé Composé",
    "imparfait": "Imparfait",
    "futur_simple": "Futur Simple",
    "conditionnel": "Conditionnel Présent",
    "subjonctif": "Subjonctif Présent"
}


def get_verb_translation(verb):
    """Get the English translation for a verb."""
    if verb in VERBS:
        return VERBS[verb].get("translation", "")
    return ""


# Each verb has: translation, rank, irregular flag, and conjugations for each tense
# Conjugations are arrays matching PRONOUNS order: [je, tu, il/elle, on, nous, vous, ils/elles]
# For passé composé, format is "auxiliary + past participle" (e.g., "ai été", "suis allé(e)")

VERBS = {
    "être": {
        "translation": "to be",
        "rank": 1,
        "irregular": True,
        "présent": ["suis", "es", "est", "est", "sommes", "êtes", "sont"],
        "passé_composé": ["ai été", "as été", "a été", "a été", "avons été", "avez été", "ont été"],
        "imparfait": ["étais", "étais", "était", "était", "étions", "étiez", "étaient"],
        "futur_simple": ["serai", "seras", "sera", "sera", "serons", "serez", "seront"],
        "conditionnel": ["serais", "serais", "serait", "serait", "serions", "seriez", "seraient"],
        "subjonctif": ["sois", "sois", "soit", "soit", "soyons", "soyez", "soient"]
    },
    "avoir": {
        "translation": "to have",
        "rank": 2,
        "irregular": True,
        "présent": ["ai", "as", "a", "a", "avons", "avez", "ont"],
        "passé_composé": ["ai eu", "as eu", "a eu", "a eu", "avons eu", "avez eu", "ont eu"],
        "imparfait": ["avais", "avais", "avait", "avait", "avions", "aviez", "avaient"],
        "futur_simple": ["aurai", "auras", "aura", "aura", "aurons", "aurez", "auront"],
        "conditionnel": ["aurais", "aurais", "aurait", "aurait", "aurions", "auriez", "auraient"],
        "subjonctif": ["aie", "aies", "ait", "ait", "ayons", "ayez", "aient"]
    },
    "faire": {
        "translation": "to do/make",
        "rank": 3,
        "irregular": True,
        "présent": ["fais", "fais", "fait", "fait", "faisons", "faites", "font"],
        "passé_composé": ["ai fait", "as fait", "a fait", "a fait", "avons fait", "avez fait", "ont fait"],
        "imparfait": ["faisais", "faisais", "faisait", "faisait", "faisions", "faisiez", "faisaient"],
        "futur_simple": ["ferai", "feras", "fera", "fera", "ferons", "ferez", "feront"],
        "conditionnel": ["ferais", "ferais", "ferait", "ferait", "ferions", "feriez", "feraient"],
        "subjonctif": ["fasse", "fasses", "fasse", "fasse", "fassions", "fassiez", "fassent"]
    },
    "dire": {
        "translation": "to say/tell",
        "rank": 4,
        "irregular": True,
        "présent": ["dis", "dis", "dit", "dit", "disons", "dites", "disent"],
        "passé_composé": ["ai dit", "as dit", "a dit", "a dit", "avons dit", "avez dit", "ont dit"],
        "imparfait": ["disais", "disais", "disait", "disait", "disions", "disiez", "disaient"],
        "futur_simple": ["dirai", "diras", "dira", "dira", "dirons", "direz", "diront"],
        "conditionnel": ["dirais", "dirais", "dirait", "dirait", "dirions", "diriez", "diraient"],
        "subjonctif": ["dise", "dises", "dise", "dise", "disions", "disiez", "disent"]
    },
    "aller": {
        "translation": "to go",
        "rank": 5,
        "irregular": True,
        "présent": ["vais", "vas", "va", "va", "allons", "allez", "vont"],
        "passé_composé": ["suis allé(e)", "es allé(e)", "est allé(e)", "est allé(e)", "sommes allé(e)s", "êtes allé(e)(s)", "sont allé(e)s"],
        "imparfait": ["allais", "allais", "allait", "allait", "allions", "alliez", "allaient"],
        "futur_simple": ["irai", "iras", "ira", "ira", "irons", "irez", "iront"],
        "conditionnel": ["irais", "irais", "irait", "irait", "irions", "iriez", "iraient"],
        "subjonctif": ["aille", "ailles", "aille", "aille", "allions", "alliez", "aillent"]
    },
    "voir": {
        "translation": "to see",
        "rank": 6,
        "irregular": True,
        "présent": ["vois", "vois", "voit", "voit", "voyons", "voyez", "voient"],
        "passé_composé": ["ai vu", "as vu", "a vu", "a vu", "avons vu", "avez vu", "ont vu"],
        "imparfait": ["voyais", "voyais", "voyait", "voyait", "voyions", "voyiez", "voyaient"],
        "futur_simple": ["verrai", "verras", "verra", "verra", "verrons", "verrez", "verront"],
        "conditionnel": ["verrais", "verrais", "verrait", "verrait", "verrions", "verriez", "verraient"],
        "subjonctif": ["voie", "voies", "voie", "voie", "voyions", "voyiez", "voient"]
    },
    "savoir": {
        "translation": "to know",
        "rank": 7,
        "irregular": True,
        "présent": ["sais", "sais", "sait", "sait", "savons", "savez", "savent"],
        "passé_composé": ["ai su", "as su", "a su", "a su", "avons su", "avez su", "ont su"],
        "imparfait": ["savais", "savais", "savait", "savait", "savions", "saviez", "savaient"],
        "futur_simple": ["saurai", "sauras", "saura", "saura", "saurons", "saurez", "sauront"],
        "conditionnel": ["saurais", "saurais", "saurait", "saurait", "saurions", "sauriez", "sauraient"],
        "subjonctif": ["sache", "saches", "sache", "sache", "sachions", "sachiez", "sachent"]
    },
    "pouvoir": {
        "translation": "to be able to/can",
        "rank": 8,
        "irregular": True,
        "présent": ["peux", "peux", "peut", "peut", "pouvons", "pouvez", "peuvent"],
        "passé_composé": ["ai pu", "as pu", "a pu", "a pu", "avons pu", "avez pu", "ont pu"],
        "imparfait": ["pouvais", "pouvais", "pouvait", "pouvait", "pouvions", "pouviez", "pouvaient"],
        "futur_simple": ["pourrai", "pourras", "pourra", "pourra", "pourrons", "pourrez", "pourront"],
        "conditionnel": ["pourrais", "pourrais", "pourrait", "pourrait", "pourrions", "pourriez", "pourraient"],
        "subjonctif": ["puisse", "puisses", "puisse", "puisse", "puissions", "puissiez", "puissent"]
    },
    "vouloir": {
        "translation": "to want",
        "rank": 9,
        "irregular": True,
        "présent": ["veux", "veux", "veut", "veut", "voulons", "voulez", "veulent"],
        "passé_composé": ["ai voulu", "as voulu", "a voulu", "a voulu", "avons voulu", "avez voulu", "ont voulu"],
        "imparfait": ["voulais", "voulais", "voulait", "voulait", "voulions", "vouliez", "voulaient"],
        "futur_simple": ["voudrai", "voudras", "voudra", "voudra", "voudrons", "voudrez", "voudront"],
        "conditionnel": ["voudrais", "voudrais", "voudrait", "voudrait", "voudrions", "voudriez", "voudraient"],
        "subjonctif": ["veuille", "veuilles", "veuille", "veuille", "voulions", "vouliez", "veuillent"]
    },
    "venir": {
        "translation": "to come",
        "rank": 10,
        "irregular": True,
        "présent": ["viens", "viens", "vient", "vient", "venons", "venez", "viennent"],
        "passé_composé": ["suis venu(e)", "es venu(e)", "est venu(e)", "est venu(e)", "sommes venu(e)s", "êtes venu(e)(s)", "sont venu(e)s"],
        "imparfait": ["venais", "venais", "venait", "venait", "venions", "veniez", "venaient"],
        "futur_simple": ["viendrai", "viendras", "viendra", "viendra", "viendrons", "viendrez", "viendront"],
        "conditionnel": ["viendrais", "viendrais", "viendrait", "viendrait", "viendrions", "viendriez", "viendraient"],
        "subjonctif": ["vienne", "viennes", "vienne", "vienne", "venions", "veniez", "viennent"]
    },
    "prendre": {
        "translation": "to take",
        "rank": 11,
        "irregular": True,
        "présent": ["prends", "prends", "prend", "prend", "prenons", "prenez", "prennent"],
        "passé_composé": ["ai pris", "as pris", "a pris", "a pris", "avons pris", "avez pris", "ont pris"],
        "imparfait": ["prenais", "prenais", "prenait", "prenait", "prenions", "preniez", "prenaient"],
        "futur_simple": ["prendrai", "prendras", "prendra", "prendra", "prendrons", "prendrez", "prendront"],
        "conditionnel": ["prendrais", "prendrais", "prendrait", "prendrait", "prendrions", "prendriez", "prendraient"],
        "subjonctif": ["prenne", "prennes", "prenne", "prenne", "prenions", "preniez", "prennent"]
    },
    "arriver": {
        "translation": "to arrive",
        "rank": 12,
        "irregular": False,
        "présent": ["arrive", "arrives", "arrive", "arrive", "arrivons", "arrivez", "arrivent"],
        "passé_composé": ["suis arrivé(e)", "es arrivé(e)", "est arrivé(e)", "est arrivé(e)", "sommes arrivé(e)s", "êtes arrivé(e)(s)", "sont arrivé(e)s"],
        "imparfait": ["arrivais", "arrivais", "arrivait", "arrivait", "arrivions", "arriviez", "arrivaient"],
        "futur_simple": ["arriverai", "arriveras", "arrivera", "arrivera", "arriverons", "arriverez", "arriveront"],
        "conditionnel": ["arriverais", "arriverais", "arriverait", "arriverait", "arriverions", "arriveriez", "arriveraient"],
        "subjonctif": ["arrive", "arrives", "arrive", "arrive", "arrivions", "arriviez", "arrivent"]
    },
    "croire": {
        "translation": "to believe",
        "rank": 13,
        "irregular": True,
        "présent": ["crois", "crois", "croit", "croit", "croyons", "croyez", "croient"],
        "passé_composé": ["ai cru", "as cru", "a cru", "a cru", "avons cru", "avez cru", "ont cru"],
        "imparfait": ["croyais", "croyais", "croyait", "croyait", "croyions", "croyiez", "croyaient"],
        "futur_simple": ["croirai", "croiras", "croira", "croira", "croirons", "croirez", "croiront"],
        "conditionnel": ["croirais", "croirais", "croirait", "croirait", "croirions", "croiriez", "croiraient"],
        "subjonctif": ["croie", "croies", "croie", "croie", "croyions", "croyiez", "croient"]
    },
    "mettre": {
        "translation": "to put",
        "rank": 14,
        "irregular": True,
        "présent": ["mets", "mets", "met", "met", "mettons", "mettez", "mettent"],
        "passé_composé": ["ai mis", "as mis", "a mis", "a mis", "avons mis", "avez mis", "ont mis"],
        "imparfait": ["mettais", "mettais", "mettait", "mettait", "mettions", "mettiez", "mettaient"],
        "futur_simple": ["mettrai", "mettras", "mettra", "mettra", "mettrons", "mettrez", "mettront"],
        "conditionnel": ["mettrais", "mettrais", "mettrait", "mettrait", "mettrions", "mettriez", "mettraient"],
        "subjonctif": ["mette", "mettes", "mette", "mette", "mettions", "mettiez", "mettent"]
    },
    "passer": {
        "translation": "to pass/spend",
        "rank": 15,
        "irregular": False,
        "présent": ["passe", "passes", "passe", "passe", "passons", "passez", "passent"],
        "passé_composé": ["ai passé", "as passé", "a passé", "a passé", "avons passé", "avez passé", "ont passé"],
        "imparfait": ["passais", "passais", "passait", "passait", "passions", "passiez", "passaient"],
        "futur_simple": ["passerai", "passeras", "passera", "passera", "passerons", "passerez", "passeront"],
        "conditionnel": ["passerais", "passerais", "passerait", "passerait", "passerions", "passeriez", "passeraient"],
        "subjonctif": ["passe", "passes", "passe", "passe", "passions", "passiez", "passent"]
    },
    "devoir": {
        "translation": "to have to/must",
        "rank": 16,
        "irregular": True,
        "présent": ["dois", "dois", "doit", "doit", "devons", "devez", "doivent"],
        "passé_composé": ["ai dû", "as dû", "a dû", "a dû", "avons dû", "avez dû", "ont dû"],
        "imparfait": ["devais", "devais", "devait", "devait", "devions", "deviez", "devaient"],
        "futur_simple": ["devrai", "devras", "devra", "devra", "devrons", "devrez", "devront"],
        "conditionnel": ["devrais", "devrais", "devrait", "devrait", "devrions", "devriez", "devraient"],
        "subjonctif": ["doive", "doives", "doive", "doive", "devions", "deviez", "doivent"]
    },
    "parler": {
        "translation": "to speak",
        "rank": 17,
        "irregular": False,
        "présent": ["parle", "parles", "parle", "parle", "parlons", "parlez", "parlent"],
        "passé_composé": ["ai parlé", "as parlé", "a parlé", "a parlé", "avons parlé", "avez parlé", "ont parlé"],
        "imparfait": ["parlais", "parlais", "parlait", "parlait", "parlions", "parliez", "parlaient"],
        "futur_simple": ["parlerai", "parleras", "parlera", "parlera", "parlerons", "parlerez", "parleront"],
        "conditionnel": ["parlerais", "parlerais", "parlerait", "parlerait", "parlerions", "parleriez", "parleraient"],
        "subjonctif": ["parle", "parles", "parle", "parle", "parlions", "parliez", "parlent"]
    },
    "trouver": {
        "translation": "to find",
        "rank": 18,
        "irregular": False,
        "présent": ["trouve", "trouves", "trouve", "trouve", "trouvons", "trouvez", "trouvent"],
        "passé_composé": ["ai trouvé", "as trouvé", "a trouvé", "a trouvé", "avons trouvé", "avez trouvé", "ont trouvé"],
        "imparfait": ["trouvais", "trouvais", "trouvait", "trouvait", "trouvions", "trouviez", "trouvaient"],
        "futur_simple": ["trouverai", "trouveras", "trouvera", "trouvera", "trouverons", "trouverez", "trouveront"],
        "conditionnel": ["trouverais", "trouverais", "trouverait", "trouverait", "trouverions", "trouveriez", "trouveraient"],
        "subjonctif": ["trouve", "trouves", "trouve", "trouve", "trouvions", "trouviez", "trouvent"]
    },
    "donner": {
        "translation": "to give",
        "rank": 19,
        "irregular": False,
        "présent": ["donne", "donnes", "donne", "donne", "donnons", "donnez", "donnent"],
        "passé_composé": ["ai donné", "as donné", "a donné", "a donné", "avons donné", "avez donné", "ont donné"],
        "imparfait": ["donnais", "donnais", "donnait", "donnait", "donnions", "donniez", "donnaient"],
        "futur_simple": ["donnerai", "donneras", "donnera", "donnera", "donnerons", "donnerez", "donneront"],
        "conditionnel": ["donnerais", "donnerais", "donnerait", "donnerait", "donnerions", "donneriez", "donneraient"],
        "subjonctif": ["donne", "donnes", "donne", "donne", "donnions", "donniez", "donnent"]
    },
    "falloir": {
        "translation": "to be necessary",
        "rank": 20,
        "irregular": True,
        "présent": ["-", "-", "faut", "faut", "-", "-", "-"],
        "passé_composé": ["-", "-", "a fallu", "a fallu", "-", "-", "-"],
        "imparfait": ["-", "-", "fallait", "fallait", "-", "-", "-"],
        "futur_simple": ["-", "-", "faudra", "faudra", "-", "-", "-"],
        "conditionnel": ["-", "-", "faudrait", "faudrait", "-", "-", "-"],
        "subjonctif": ["-", "-", "faille", "faille", "-", "-", "-"]
    },
    "comprendre": {
        "translation": "to understand",
        "rank": 21,
        "irregular": True,
        "présent": ["comprends", "comprends", "comprend", "comprend", "comprenons", "comprenez", "comprennent"],
        "passé_composé": ["ai compris", "as compris", "a compris", "a compris", "avons compris", "avez compris", "ont compris"],
        "imparfait": ["comprenais", "comprenais", "comprenait", "comprenait", "comprenions", "compreniez", "comprenaient"],
        "futur_simple": ["comprendrai", "comprendras", "comprendra", "comprendra", "comprendrons", "comprendrez", "comprendront"],
        "conditionnel": ["comprendrais", "comprendrais", "comprendrait", "comprendrait", "comprendrions", "comprendriez", "comprendraient"],
        "subjonctif": ["comprenne", "comprennes", "comprenne", "comprenne", "comprenions", "compreniez", "comprennent"]
    },
    "connaître": {
        "translation": "to know (person/place)",
        "rank": 22,
        "irregular": True,
        "présent": ["connais", "connais", "connaît", "connaît", "connaissons", "connaissez", "connaissent"],
        "passé_composé": ["ai connu", "as connu", "a connu", "a connu", "avons connu", "avez connu", "ont connu"],
        "imparfait": ["connaissais", "connaissais", "connaissait", "connaissait", "connaissions", "connaissiez", "connaissaient"],
        "futur_simple": ["connaîtrai", "connaîtras", "connaîtra", "connaîtra", "connaîtrons", "connaîtrez", "connaîtront"],
        "conditionnel": ["connaîtrais", "connaîtrais", "connaîtrait", "connaîtrait", "connaîtrions", "connaîtriez", "connaîtraient"],
        "subjonctif": ["connaisse", "connaisses", "connaisse", "connaisse", "connaissions", "connaissiez", "connaissent"]
    },
    "partir": {
        "translation": "to leave",
        "rank": 23,
        "irregular": True,
        "présent": ["pars", "pars", "part", "part", "partons", "partez", "partent"],
        "passé_composé": ["suis parti(e)", "es parti(e)", "est parti(e)", "est parti(e)", "sommes parti(e)s", "êtes parti(e)(s)", "sont parti(e)s"],
        "imparfait": ["partais", "partais", "partait", "partait", "partions", "partiez", "partaient"],
        "futur_simple": ["partirai", "partiras", "partira", "partira", "partirons", "partirez", "partiront"],
        "conditionnel": ["partirais", "partirais", "partirait", "partirait", "partirions", "partiriez", "partiraient"],
        "subjonctif": ["parte", "partes", "parte", "parte", "partions", "partiez", "partent"]
    },
    "demander": {
        "translation": "to ask",
        "rank": 24,
        "irregular": False,
        "présent": ["demande", "demandes", "demande", "demande", "demandons", "demandez", "demandent"],
        "passé_composé": ["ai demandé", "as demandé", "a demandé", "a demandé", "avons demandé", "avez demandé", "ont demandé"],
        "imparfait": ["demandais", "demandais", "demandait", "demandait", "demandions", "demandiez", "demandaient"],
        "futur_simple": ["demanderai", "demanderas", "demandera", "demandera", "demanderons", "demanderez", "demanderont"],
        "conditionnel": ["demanderais", "demanderais", "demanderait", "demanderait", "demanderions", "demanderiez", "demanderaient"],
        "subjonctif": ["demande", "demandes", "demande", "demande", "demandions", "demandiez", "demandent"]
    },
    "tenir": {
        "translation": "to hold",
        "rank": 25,
        "irregular": True,
        "présent": ["tiens", "tiens", "tient", "tient", "tenons", "tenez", "tiennent"],
        "passé_composé": ["ai tenu", "as tenu", "a tenu", "a tenu", "avons tenu", "avez tenu", "ont tenu"],
        "imparfait": ["tenais", "tenais", "tenait", "tenait", "tenions", "teniez", "tenaient"],
        "futur_simple": ["tiendrai", "tiendras", "tiendra", "tiendra", "tiendrons", "tiendrez", "tiendront"],
        "conditionnel": ["tiendrais", "tiendrais", "tiendrait", "tiendrait", "tiendrions", "tiendriez", "tiendraient"],
        "subjonctif": ["tienne", "tiennes", "tienne", "tienne", "tenions", "teniez", "tiennent"]
    },
    "sembler": {
        "translation": "to seem",
        "rank": 26,
        "irregular": False,
        "présent": ["semble", "sembles", "semble", "semble", "semblons", "semblez", "semblent"],
        "passé_composé": ["ai semblé", "as semblé", "a semblé", "a semblé", "avons semblé", "avez semblé", "ont semblé"],
        "imparfait": ["semblais", "semblais", "semblait", "semblait", "semblions", "sembliez", "semblaient"],
        "futur_simple": ["semblerai", "sembleras", "semblera", "semblera", "semblerons", "semblerez", "sembleront"],
        "conditionnel": ["semblerais", "semblerais", "semblerait", "semblerait", "semblerions", "sembleriez", "sembleraient"],
        "subjonctif": ["semble", "sembles", "semble", "semble", "semblions", "sembliez", "semblent"]
    },
    "laisser": {
        "translation": "to leave/let",
        "rank": 27,
        "irregular": False,
        "présent": ["laisse", "laisses", "laisse", "laisse", "laissons", "laissez", "laissent"],
        "passé_composé": ["ai laissé", "as laissé", "a laissé", "a laissé", "avons laissé", "avez laissé", "ont laissé"],
        "imparfait": ["laissais", "laissais", "laissait", "laissait", "laissions", "laissiez", "laissaient"],
        "futur_simple": ["laisserai", "laisseras", "laissera", "laissera", "laisserons", "laisserez", "laisseront"],
        "conditionnel": ["laisserais", "laisserais", "laisserait", "laisserait", "laisserions", "laisseriez", "laisseraient"],
        "subjonctif": ["laisse", "laisses", "laisse", "laisse", "laissions", "laissiez", "laissent"]
    },
    "rester": {
        "translation": "to stay",
        "rank": 28,
        "irregular": False,
        "présent": ["reste", "restes", "reste", "reste", "restons", "restez", "restent"],
        "passé_composé": ["suis resté(e)", "es resté(e)", "est resté(e)", "est resté(e)", "sommes resté(e)s", "êtes resté(e)(s)", "sont resté(e)s"],
        "imparfait": ["restais", "restais", "restait", "restait", "restions", "restiez", "restaient"],
        "futur_simple": ["resterai", "resteras", "restera", "restera", "resterons", "resterez", "resteront"],
        "conditionnel": ["resterais", "resterais", "resterait", "resterait", "resterions", "resteriez", "resteraient"],
        "subjonctif": ["reste", "restes", "reste", "reste", "restions", "restiez", "restent"]
    },
    "penser": {
        "translation": "to think",
        "rank": 29,
        "irregular": False,
        "présent": ["pense", "penses", "pense", "pense", "pensons", "pensez", "pensent"],
        "passé_composé": ["ai pensé", "as pensé", "a pensé", "a pensé", "avons pensé", "avez pensé", "ont pensé"],
        "imparfait": ["pensais", "pensais", "pensait", "pensait", "pensions", "pensiez", "pensaient"],
        "futur_simple": ["penserai", "penseras", "pensera", "pensera", "penserons", "penserez", "penseront"],
        "conditionnel": ["penserais", "penserais", "penserait", "penserait", "penserions", "penseriez", "penseraient"],
        "subjonctif": ["pense", "penses", "pense", "pense", "pensions", "pensiez", "pensent"]
    },
    "entendre": {
        "translation": "to hear",
        "rank": 30,
        "irregular": False,
        "présent": ["entends", "entends", "entend", "entend", "entendons", "entendez", "entendent"],
        "passé_composé": ["ai entendu", "as entendu", "a entendu", "a entendu", "avons entendu", "avez entendu", "ont entendu"],
        "imparfait": ["entendais", "entendais", "entendait", "entendait", "entendions", "entendiez", "entendaient"],
        "futur_simple": ["entendrai", "entendras", "entendra", "entendra", "entendrons", "entendrez", "entendront"],
        "conditionnel": ["entendrais", "entendrais", "entendrait", "entendrait", "entendrions", "entendriez", "entendraient"],
        "subjonctif": ["entende", "entendes", "entende", "entende", "entendions", "entendiez", "entendent"]
    },
    "regarder": {
        "translation": "to watch/look at",
        "rank": 31,
        "irregular": False,
        "présent": ["regarde", "regardes", "regarde", "regarde", "regardons", "regardez", "regardent"],
        "passé_composé": ["ai regardé", "as regardé", "a regardé", "a regardé", "avons regardé", "avez regardé", "ont regardé"],
        "imparfait": ["regardais", "regardais", "regardait", "regardait", "regardions", "regardiez", "regardaient"],
        "futur_simple": ["regarderai", "regarderas", "regardera", "regardera", "regarderons", "regarderez", "regarderont"],
        "conditionnel": ["regarderais", "regarderais", "regarderait", "regarderait", "regarderions", "regarderiez", "regarderaient"],
        "subjonctif": ["regarde", "regardes", "regarde", "regarde", "regardions", "regardiez", "regardent"]
    },
    "répondre": {
        "translation": "to answer",
        "rank": 32,
        "irregular": False,
        "présent": ["réponds", "réponds", "répond", "répond", "répondons", "répondez", "répondent"],
        "passé_composé": ["ai répondu", "as répondu", "a répondu", "a répondu", "avons répondu", "avez répondu", "ont répondu"],
        "imparfait": ["répondais", "répondais", "répondait", "répondait", "répondions", "répondiez", "répondaient"],
        "futur_simple": ["répondrai", "répondras", "répondra", "répondra", "répondrons", "répondrez", "répondront"],
        "conditionnel": ["répondrais", "répondrais", "répondrait", "répondrait", "répondrions", "répondriez", "répondraient"],
        "subjonctif": ["réponde", "répondes", "réponde", "réponde", "répondions", "répondiez", "répondent"]
    },
    "rendre": {
        "translation": "to give back/render",
        "rank": 33,
        "irregular": False,
        "présent": ["rends", "rends", "rend", "rend", "rendons", "rendez", "rendent"],
        "passé_composé": ["ai rendu", "as rendu", "a rendu", "a rendu", "avons rendu", "avez rendu", "ont rendu"],
        "imparfait": ["rendais", "rendais", "rendait", "rendait", "rendions", "rendiez", "rendaient"],
        "futur_simple": ["rendrai", "rendras", "rendra", "rendra", "rendrons", "rendrez", "rendront"],
        "conditionnel": ["rendrais", "rendrais", "rendrait", "rendrait", "rendrions", "rendriez", "rendraient"],
        "subjonctif": ["rende", "rendes", "rende", "rende", "rendions", "rendiez", "rendent"]
    },
    "sentir": {
        "translation": "to feel/smell",
        "rank": 34,
        "irregular": True,
        "présent": ["sens", "sens", "sent", "sent", "sentons", "sentez", "sentent"],
        "passé_composé": ["ai senti", "as senti", "a senti", "a senti", "avons senti", "avez senti", "ont senti"],
        "imparfait": ["sentais", "sentais", "sentait", "sentait", "sentions", "sentiez", "sentaient"],
        "futur_simple": ["sentirai", "sentiras", "sentira", "sentira", "sentirons", "sentirez", "sentiront"],
        "conditionnel": ["sentirais", "sentirais", "sentirait", "sentirait", "sentirions", "sentiriez", "sentiraient"],
        "subjonctif": ["sente", "sentes", "sente", "sente", "sentions", "sentiez", "sentent"]
    },
    "attendre": {
        "translation": "to wait",
        "rank": 35,
        "irregular": False,
        "présent": ["attends", "attends", "attend", "attend", "attendons", "attendez", "attendent"],
        "passé_composé": ["ai attendu", "as attendu", "a attendu", "a attendu", "avons attendu", "avez attendu", "ont attendu"],
        "imparfait": ["attendais", "attendais", "attendait", "attendait", "attendions", "attendiez", "attendaient"],
        "futur_simple": ["attendrai", "attendras", "attendra", "attendra", "attendrons", "attendrez", "attendront"],
        "conditionnel": ["attendrais", "attendrais", "attendrait", "attendrait", "attendrions", "attendriez", "attendraient"],
        "subjonctif": ["attende", "attendes", "attende", "attende", "attendions", "attendiez", "attendent"]
    },
    "vivre": {
        "translation": "to live",
        "rank": 36,
        "irregular": True,
        "présent": ["vis", "vis", "vit", "vit", "vivons", "vivez", "vivent"],
        "passé_composé": ["ai vécu", "as vécu", "a vécu", "a vécu", "avons vécu", "avez vécu", "ont vécu"],
        "imparfait": ["vivais", "vivais", "vivait", "vivait", "vivions", "viviez", "vivaient"],
        "futur_simple": ["vivrai", "vivras", "vivra", "vivra", "vivrons", "vivrez", "vivront"],
        "conditionnel": ["vivrais", "vivrais", "vivrait", "vivrait", "vivrions", "vivriez", "vivraient"],
        "subjonctif": ["vive", "vives", "vive", "vive", "vivions", "viviez", "vivent"]
    },
    "chercher": {
        "translation": "to look for",
        "rank": 37,
        "irregular": False,
        "présent": ["cherche", "cherches", "cherche", "cherche", "cherchons", "cherchez", "cherchent"],
        "passé_composé": ["ai cherché", "as cherché", "a cherché", "a cherché", "avons cherché", "avez cherché", "ont cherché"],
        "imparfait": ["cherchais", "cherchais", "cherchait", "cherchait", "cherchions", "cherchiez", "cherchaient"],
        "futur_simple": ["chercherai", "chercheras", "cherchera", "cherchera", "chercherons", "chercherez", "chercheront"],
        "conditionnel": ["chercherais", "chercherais", "chercherait", "chercherait", "chercherions", "chercheriez", "chercheraient"],
        "subjonctif": ["cherche", "cherches", "cherche", "cherche", "cherchions", "cherchiez", "cherchent"]
    },
    "sortir": {
        "translation": "to go out",
        "rank": 38,
        "irregular": True,
        "présent": ["sors", "sors", "sort", "sort", "sortons", "sortez", "sortent"],
        "passé_composé": ["suis sorti(e)", "es sorti(e)", "est sorti(e)", "est sorti(e)", "sommes sorti(e)s", "êtes sorti(e)(s)", "sont sorti(e)s"],
        "imparfait": ["sortais", "sortais", "sortait", "sortait", "sortions", "sortiez", "sortaient"],
        "futur_simple": ["sortirai", "sortiras", "sortira", "sortira", "sortirons", "sortirez", "sortiront"],
        "conditionnel": ["sortirais", "sortirais", "sortirait", "sortirait", "sortirions", "sortiriez", "sortiraient"],
        "subjonctif": ["sorte", "sortes", "sorte", "sorte", "sortions", "sortiez", "sortent"]
    },
    "perdre": {
        "translation": "to lose",
        "rank": 39,
        "irregular": False,
        "présent": ["perds", "perds", "perd", "perd", "perdons", "perdez", "perdent"],
        "passé_composé": ["ai perdu", "as perdu", "a perdu", "a perdu", "avons perdu", "avez perdu", "ont perdu"],
        "imparfait": ["perdais", "perdais", "perdait", "perdait", "perdions", "perdiez", "perdaient"],
        "futur_simple": ["perdrai", "perdras", "perdra", "perdra", "perdrons", "perdrez", "perdront"],
        "conditionnel": ["perdrais", "perdrais", "perdrait", "perdrait", "perdrions", "perdriez", "perdraient"],
        "subjonctif": ["perde", "perdes", "perde", "perde", "perdions", "perdiez", "perdent"]
    },
    "revenir": {
        "translation": "to come back",
        "rank": 40,
        "irregular": True,
        "présent": ["reviens", "reviens", "revient", "revient", "revenons", "revenez", "reviennent"],
        "passé_composé": ["suis revenu(e)", "es revenu(e)", "est revenu(e)", "est revenu(e)", "sommes revenu(e)s", "êtes revenu(e)(s)", "sont revenu(e)s"],
        "imparfait": ["revenais", "revenais", "revenait", "revenait", "revenions", "reveniez", "revenaient"],
        "futur_simple": ["reviendrai", "reviendras", "reviendra", "reviendra", "reviendrons", "reviendrez", "reviendront"],
        "conditionnel": ["reviendrais", "reviendrais", "reviendrait", "reviendrait", "reviendrions", "reviendriez", "reviendraient"],
        "subjonctif": ["revienne", "reviennes", "revienne", "revienne", "revenions", "reveniez", "reviennent"]
    },
    "porter": {
        "translation": "to carry/wear",
        "rank": 41,
        "irregular": False,
        "présent": ["porte", "portes", "porte", "porte", "portons", "portez", "portent"],
        "passé_composé": ["ai porté", "as porté", "a porté", "a porté", "avons porté", "avez porté", "ont porté"],
        "imparfait": ["portais", "portais", "portait", "portait", "portions", "portiez", "portaient"],
        "futur_simple": ["porterai", "porteras", "portera", "portera", "porterons", "porterez", "porteront"],
        "conditionnel": ["porterais", "porterais", "porterait", "porterait", "porterions", "porteriez", "porteraient"],
        "subjonctif": ["porte", "portes", "porte", "porte", "portions", "portiez", "portent"]
    },
    "écrire": {
        "translation": "to write",
        "rank": 42,
        "irregular": True,
        "présent": ["écris", "écris", "écrit", "écrit", "écrivons", "écrivez", "écrivent"],
        "passé_composé": ["ai écrit", "as écrit", "a écrit", "a écrit", "avons écrit", "avez écrit", "ont écrit"],
        "imparfait": ["écrivais", "écrivais", "écrivait", "écrivait", "écrivions", "écriviez", "écrivaient"],
        "futur_simple": ["écrirai", "écriras", "écrira", "écrira", "écrirons", "écrirez", "écriront"],
        "conditionnel": ["écrirais", "écrirais", "écrirait", "écrirait", "écririons", "écririez", "écriraient"],
        "subjonctif": ["écrive", "écrives", "écrive", "écrive", "écrivions", "écriviez", "écrivent"]
    },
    "devenir": {
        "translation": "to become",
        "rank": 43,
        "irregular": True,
        "présent": ["deviens", "deviens", "devient", "devient", "devenons", "devenez", "deviennent"],
        "passé_composé": ["suis devenu(e)", "es devenu(e)", "est devenu(e)", "est devenu(e)", "sommes devenu(e)s", "êtes devenu(e)(s)", "sont devenu(e)s"],
        "imparfait": ["devenais", "devenais", "devenait", "devenait", "devenions", "deveniez", "devenaient"],
        "futur_simple": ["deviendrai", "deviendras", "deviendra", "deviendra", "deviendrons", "deviendrez", "deviendront"],
        "conditionnel": ["deviendrais", "deviendrais", "deviendrait", "deviendrait", "deviendrions", "deviendriez", "deviendraient"],
        "subjonctif": ["devienne", "deviennes", "devienne", "devienne", "devenions", "deveniez", "deviennent"]
    },
    "monter": {
        "translation": "to go up/climb",
        "rank": 44,
        "irregular": False,
        "présent": ["monte", "montes", "monte", "monte", "montons", "montez", "montent"],
        "passé_composé": ["suis monté(e)", "es monté(e)", "est monté(e)", "est monté(e)", "sommes monté(e)s", "êtes monté(e)(s)", "sont monté(e)s"],
        "imparfait": ["montais", "montais", "montait", "montait", "montions", "montiez", "montaient"],
        "futur_simple": ["monterai", "monteras", "montera", "montera", "monterons", "monterez", "monteront"],
        "conditionnel": ["monterais", "monterais", "monterait", "monterait", "monterions", "monteriez", "monteraient"],
        "subjonctif": ["monte", "montes", "monte", "monte", "montions", "montiez", "montent"]
    },
    "montrer": {
        "translation": "to show",
        "rank": 45,
        "irregular": False,
        "présent": ["montre", "montres", "montre", "montre", "montrons", "montrez", "montrent"],
        "passé_composé": ["ai montré", "as montré", "a montré", "a montré", "avons montré", "avez montré", "ont montré"],
        "imparfait": ["montrais", "montrais", "montrait", "montrait", "montrions", "montriez", "montraient"],
        "futur_simple": ["montrerai", "montreras", "montrera", "montrera", "montrerons", "montrerez", "montreront"],
        "conditionnel": ["montrerais", "montrerais", "montrerait", "montrerait", "montrerions", "montreriez", "montreraient"],
        "subjonctif": ["montre", "montres", "montre", "montre", "montrions", "montriez", "montrent"]
    },
    "suivre": {
        "translation": "to follow",
        "rank": 46,
        "irregular": True,
        "présent": ["suis", "suis", "suit", "suit", "suivons", "suivez", "suivent"],
        "passé_composé": ["ai suivi", "as suivi", "a suivi", "a suivi", "avons suivi", "avez suivi", "ont suivi"],
        "imparfait": ["suivais", "suivais", "suivait", "suivait", "suivions", "suiviez", "suivaient"],
        "futur_simple": ["suivrai", "suivras", "suivra", "suivra", "suivrons", "suivrez", "suivront"],
        "conditionnel": ["suivrais", "suivrais", "suivrait", "suivrait", "suivrions", "suivriez", "suivraient"],
        "subjonctif": ["suive", "suives", "suive", "suive", "suivions", "suiviez", "suivent"]
    },
    "commencer": {
        "translation": "to begin",
        "rank": 47,
        "irregular": False,
        "présent": ["commence", "commences", "commence", "commence", "commençons", "commencez", "commencent"],
        "passé_composé": ["ai commencé", "as commencé", "a commencé", "a commencé", "avons commencé", "avez commencé", "ont commencé"],
        "imparfait": ["commençais", "commençais", "commençait", "commençait", "commencions", "commenciez", "commençaient"],
        "futur_simple": ["commencerai", "commenceras", "commencera", "commencera", "commencerons", "commencerez", "commenceront"],
        "conditionnel": ["commencerais", "commencerais", "commencerait", "commencerait", "commencerions", "commenceriez", "commenceraient"],
        "subjonctif": ["commence", "commences", "commence", "commence", "commencions", "commenciez", "commencent"]
    },
    "compter": {
        "translation": "to count",
        "rank": 48,
        "irregular": False,
        "présent": ["compte", "comptes", "compte", "compte", "comptons", "comptez", "comptent"],
        "passé_composé": ["ai compté", "as compté", "a compté", "a compté", "avons compté", "avez compté", "ont compté"],
        "imparfait": ["comptais", "comptais", "comptait", "comptait", "comptions", "comptiez", "comptaient"],
        "futur_simple": ["compterai", "compteras", "comptera", "comptera", "compterons", "compterez", "compteront"],
        "conditionnel": ["compterais", "compterais", "compterait", "compterait", "compterions", "compteriez", "compteraient"],
        "subjonctif": ["compte", "comptes", "compte", "compte", "comptions", "comptiez", "comptent"]
    },
    "entrer": {
        "translation": "to enter",
        "rank": 49,
        "irregular": False,
        "présent": ["entre", "entres", "entre", "entre", "entrons", "entrez", "entrent"],
        "passé_composé": ["suis entré(e)", "es entré(e)", "est entré(e)", "est entré(e)", "sommes entré(e)s", "êtes entré(e)(s)", "sont entré(e)s"],
        "imparfait": ["entrais", "entrais", "entrait", "entrait", "entrions", "entriez", "entraient"],
        "futur_simple": ["entrerai", "entreras", "entrera", "entrera", "entrerons", "entrerez", "entreront"],
        "conditionnel": ["entrerais", "entrerais", "entrerait", "entrerait", "entrerions", "entreriez", "entreraient"],
        "subjonctif": ["entre", "entres", "entre", "entre", "entrions", "entriez", "entrent"]
    },
    "mourir": {
        "translation": "to die",
        "rank": 50,
        "irregular": True,
        "présent": ["meurs", "meurs", "meurt", "meurt", "mourons", "mourez", "meurent"],
        "passé_composé": ["suis mort(e)", "es mort(e)", "est mort(e)", "est mort(e)", "sommes mort(e)s", "êtes mort(e)(s)", "sont mort(e)s"],
        "imparfait": ["mourais", "mourais", "mourait", "mourait", "mourions", "mouriez", "mouraient"],
        "futur_simple": ["mourrai", "mourras", "mourra", "mourra", "mourrons", "mourrez", "mourront"],
        "conditionnel": ["mourrais", "mourrais", "mourrait", "mourrait", "mourrions", "mourriez", "mourraient"],
        "subjonctif": ["meure", "meures", "meure", "meure", "mourions", "mouriez", "meurent"]
    },
    "ouvrir": {
        "translation": "to open",
        "rank": 51,
        "irregular": True,
        "présent": ["ouvre", "ouvres", "ouvre", "ouvre", "ouvrons", "ouvrez", "ouvrent"],
        "passé_composé": ["ai ouvert", "as ouvert", "a ouvert", "a ouvert", "avons ouvert", "avez ouvert", "ont ouvert"],
        "imparfait": ["ouvrais", "ouvrais", "ouvrait", "ouvrait", "ouvrions", "ouvriez", "ouvraient"],
        "futur_simple": ["ouvrirai", "ouvriras", "ouvrira", "ouvrira", "ouvrirons", "ouvrirez", "ouvriront"],
        "conditionnel": ["ouvrirais", "ouvrirais", "ouvrirait", "ouvrirait", "ouvririons", "ouvririez", "ouvriraient"],
        "subjonctif": ["ouvre", "ouvres", "ouvre", "ouvre", "ouvrions", "ouvriez", "ouvrent"]
    },
    "lire": {
        "translation": "to read",
        "rank": 52,
        "irregular": True,
        "présent": ["lis", "lis", "lit", "lit", "lisons", "lisez", "lisent"],
        "passé_composé": ["ai lu", "as lu", "a lu", "a lu", "avons lu", "avez lu", "ont lu"],
        "imparfait": ["lisais", "lisais", "lisait", "lisait", "lisions", "lisiez", "lisaient"],
        "futur_simple": ["lirai", "liras", "lira", "lira", "lirons", "lirez", "liront"],
        "conditionnel": ["lirais", "lirais", "lirait", "lirait", "lirions", "liriez", "liraient"],
        "subjonctif": ["lise", "lises", "lise", "lise", "lisions", "lisiez", "lisent"]
    },
    "arrêter": {
        "translation": "to stop",
        "rank": 53,
        "irregular": False,
        "présent": ["arrête", "arrêtes", "arrête", "arrête", "arrêtons", "arrêtez", "arrêtent"],
        "passé_composé": ["ai arrêté", "as arrêté", "a arrêté", "a arrêté", "avons arrêté", "avez arrêté", "ont arrêté"],
        "imparfait": ["arrêtais", "arrêtais", "arrêtait", "arrêtait", "arrêtions", "arrêtiez", "arrêtaient"],
        "futur_simple": ["arrêterai", "arrêteras", "arrêtera", "arrêtera", "arrêterons", "arrêterez", "arrêteront"],
        "conditionnel": ["arrêterais", "arrêterais", "arrêterait", "arrêterait", "arrêterions", "arrêteriez", "arrêteraient"],
        "subjonctif": ["arrête", "arrêtes", "arrête", "arrête", "arrêtions", "arrêtiez", "arrêtent"]
    },
    "servir": {
        "translation": "to serve",
        "rank": 54,
        "irregular": True,
        "présent": ["sers", "sers", "sert", "sert", "servons", "servez", "servent"],
        "passé_composé": ["ai servi", "as servi", "a servi", "a servi", "avons servi", "avez servi", "ont servi"],
        "imparfait": ["servais", "servais", "servait", "servait", "servions", "serviez", "servaient"],
        "futur_simple": ["servirai", "serviras", "servira", "servira", "servirons", "servirez", "serviront"],
        "conditionnel": ["servirais", "servirais", "servirait", "servirait", "servirions", "serviriez", "serviraient"],
        "subjonctif": ["serve", "serves", "serve", "serve", "servions", "serviez", "servent"]
    },
    "jeter": {
        "translation": "to throw",
        "rank": 55,
        "irregular": False,
        "présent": ["jette", "jettes", "jette", "jette", "jetons", "jetez", "jettent"],
        "passé_composé": ["ai jeté", "as jeté", "a jeté", "a jeté", "avons jeté", "avez jeté", "ont jeté"],
        "imparfait": ["jetais", "jetais", "jetait", "jetait", "jetions", "jetiez", "jetaient"],
        "futur_simple": ["jetterai", "jetteras", "jettera", "jettera", "jetterons", "jetterez", "jetteront"],
        "conditionnel": ["jetterais", "jetterais", "jetterait", "jetterait", "jetterions", "jetteriez", "jetteraient"],
        "subjonctif": ["jette", "jettes", "jette", "jette", "jetions", "jetiez", "jettent"]
    },
    "recevoir": {
        "translation": "to receive",
        "rank": 56,
        "irregular": True,
        "présent": ["reçois", "reçois", "reçoit", "reçoit", "recevons", "recevez", "reçoivent"],
        "passé_composé": ["ai reçu", "as reçu", "a reçu", "a reçu", "avons reçu", "avez reçu", "ont reçu"],
        "imparfait": ["recevais", "recevais", "recevait", "recevait", "recevions", "receviez", "recevaient"],
        "futur_simple": ["recevrai", "recevras", "recevra", "recevra", "recevrons", "recevrez", "recevront"],
        "conditionnel": ["recevrais", "recevrais", "recevrait", "recevrait", "recevrions", "recevriez", "recevraient"],
        "subjonctif": ["reçoive", "reçoives", "reçoive", "reçoive", "recevions", "receviez", "reçoivent"]
    },
    "finir": {
        "translation": "to finish",
        "rank": 57,
        "irregular": False,
        "présent": ["finis", "finis", "finit", "finit", "finissons", "finissez", "finissent"],
        "passé_composé": ["ai fini", "as fini", "a fini", "a fini", "avons fini", "avez fini", "ont fini"],
        "imparfait": ["finissais", "finissais", "finissait", "finissait", "finissions", "finissiez", "finissaient"],
        "futur_simple": ["finirai", "finiras", "finira", "finira", "finirons", "finirez", "finiront"],
        "conditionnel": ["finirais", "finirais", "finirait", "finirait", "finirions", "finiriez", "finiraient"],
        "subjonctif": ["finisse", "finisses", "finisse", "finisse", "finissions", "finissiez", "finissent"]
    },
    "appeler": {
        "translation": "to call",
        "rank": 58,
        "irregular": False,
        "présent": ["appelle", "appelles", "appelle", "appelle", "appelons", "appelez", "appellent"],
        "passé_composé": ["ai appelé", "as appelé", "a appelé", "a appelé", "avons appelé", "avez appelé", "ont appelé"],
        "imparfait": ["appelais", "appelais", "appelait", "appelait", "appelions", "appeliez", "appelaient"],
        "futur_simple": ["appellerai", "appelleras", "appellera", "appellera", "appellerons", "appellerez", "appelleront"],
        "conditionnel": ["appellerais", "appellerais", "appellerait", "appellerait", "appellerions", "appelleriez", "appelleraient"],
        "subjonctif": ["appelle", "appelles", "appelle", "appelle", "appelions", "appeliez", "appellent"]
    },
    "permettre": {
        "translation": "to allow",
        "rank": 59,
        "irregular": True,
        "présent": ["permets", "permets", "permet", "permet", "permettons", "permettez", "permettent"],
        "passé_composé": ["ai permis", "as permis", "a permis", "a permis", "avons permis", "avez permis", "ont permis"],
        "imparfait": ["permettais", "permettais", "permettait", "permettait", "permettions", "permettiez", "permettaient"],
        "futur_simple": ["permettrai", "permettras", "permettra", "permettra", "permettrons", "permettrez", "permettront"],
        "conditionnel": ["permettrais", "permettrais", "permettrait", "permettrait", "permettrions", "permettriez", "permettraient"],
        "subjonctif": ["permette", "permettes", "permette", "permette", "permettions", "permettiez", "permettent"]
    },
    "s'asseoir": {
        "translation": "to sit down",
        "rank": 60,
        "irregular": True,
        "présent": ["m'assieds", "t'assieds", "s'assied", "s'assied", "nous asseyons", "vous asseyez", "s'asseyent"],
        "passé_composé": ["me suis assis(e)", "t'es assis(e)", "s'est assis(e)", "s'est assis(e)", "nous sommes assis(es)", "vous êtes assis(es)", "se sont assis(es)"],
        "imparfait": ["m'asseyais", "t'asseyais", "s'asseyait", "s'asseyait", "nous asseyions", "vous asseyiez", "s'asseyaient"],
        "futur_simple": ["m'assiérai", "t'assiéras", "s'assiéra", "s'assiéra", "nous assiérons", "vous assiérez", "s'assiéront"],
        "conditionnel": ["m'assiérais", "t'assiérais", "s'assiérait", "s'assiérait", "nous assiérions", "vous assiériez", "s'assiéraient"],
        "subjonctif": ["m'asseye", "t'asseyes", "s'asseye", "s'asseye", "nous asseyions", "vous asseyiez", "s'asseyent"]
    },
    "marcher": {
        "translation": "to walk",
        "rank": 61,
        "irregular": False,
        "présent": ["marche", "marches", "marche", "marche", "marchons", "marchez", "marchent"],
        "passé_composé": ["ai marché", "as marché", "a marché", "a marché", "avons marché", "avez marché", "ont marché"],
        "imparfait": ["marchais", "marchais", "marchait", "marchait", "marchions", "marchiez", "marchaient"],
        "futur_simple": ["marcherai", "marcheras", "marchera", "marchera", "marcherons", "marcherez", "marcheront"],
        "conditionnel": ["marcherais", "marcherais", "marcherait", "marcherait", "marcherions", "marcheriez", "marcheraient"],
        "subjonctif": ["marche", "marches", "marche", "marche", "marchions", "marchiez", "marchent"]
    },
    "rappeler": {
        "translation": "to recall/call back",
        "rank": 62,
        "irregular": False,
        "présent": ["rappelle", "rappelles", "rappelle", "rappelle", "rappelons", "rappelez", "rappellent"],
        "passé_composé": ["ai rappelé", "as rappelé", "a rappelé", "a rappelé", "avons rappelé", "avez rappelé", "ont rappelé"],
        "imparfait": ["rappelais", "rappelais", "rappelait", "rappelait", "rappelions", "rappeliez", "rappelaient"],
        "futur_simple": ["rappellerai", "rappelleras", "rappellera", "rappellera", "rappellerons", "rappellerez", "rappelleront"],
        "conditionnel": ["rappellerais", "rappellerais", "rappellerait", "rappellerait", "rappellerions", "rappelleriez", "rappelleraient"],
        "subjonctif": ["rappelle", "rappelles", "rappelle", "rappelle", "rappelions", "rappeliez", "rappellent"]
    },
    "accepter": {
        "translation": "to accept",
        "rank": 63,
        "irregular": False,
        "présent": ["accepte", "acceptes", "accepte", "accepte", "acceptons", "acceptez", "acceptent"],
        "passé_composé": ["ai accepté", "as accepté", "a accepté", "a accepté", "avons accepté", "avez accepté", "ont accepté"],
        "imparfait": ["acceptais", "acceptais", "acceptait", "acceptait", "acceptions", "acceptiez", "acceptaient"],
        "futur_simple": ["accepterai", "accepteras", "acceptera", "acceptera", "accepterons", "accepterez", "accepteront"],
        "conditionnel": ["accepterais", "accepterais", "accepterait", "accepterait", "accepterions", "accepteriez", "accepteraient"],
        "subjonctif": ["accepte", "acceptes", "accepte", "accepte", "acceptions", "acceptiez", "acceptent"]
    },
    "aimer": {
        "translation": "to love/like",
        "rank": 64,
        "irregular": False,
        "présent": ["aime", "aimes", "aime", "aime", "aimons", "aimez", "aiment"],
        "passé_composé": ["ai aimé", "as aimé", "a aimé", "a aimé", "avons aimé", "avez aimé", "ont aimé"],
        "imparfait": ["aimais", "aimais", "aimait", "aimait", "aimions", "aimiez", "aimaient"],
        "futur_simple": ["aimerai", "aimeras", "aimera", "aimera", "aimerons", "aimerez", "aimeront"],
        "conditionnel": ["aimerais", "aimerais", "aimerait", "aimerait", "aimerions", "aimeriez", "aimeraient"],
        "subjonctif": ["aime", "aimes", "aime", "aime", "aimions", "aimiez", "aiment"]
    },
    "ajouter": {
        "translation": "to add",
        "rank": 65,
        "irregular": False,
        "présent": ["ajoute", "ajoutes", "ajoute", "ajoute", "ajoutons", "ajoutez", "ajoutent"],
        "passé_composé": ["ai ajouté", "as ajouté", "a ajouté", "a ajouté", "avons ajouté", "avez ajouté", "ont ajouté"],
        "imparfait": ["ajoutais", "ajoutais", "ajoutait", "ajoutait", "ajoutions", "ajoutiez", "ajoutaient"],
        "futur_simple": ["ajouterai", "ajouteras", "ajoutera", "ajoutera", "ajouterons", "ajouterez", "ajouteront"],
        "conditionnel": ["ajouterais", "ajouterais", "ajouterait", "ajouterait", "ajouterions", "ajouteriez", "ajouteraient"],
        "subjonctif": ["ajoute", "ajoutes", "ajoute", "ajoute", "ajoutions", "ajoutiez", "ajoutent"]
    },
    "apporter": {
        "translation": "to bring",
        "rank": 66,
        "irregular": False,
        "présent": ["apporte", "apportes", "apporte", "apporte", "apportons", "apportez", "apportent"],
        "passé_composé": ["ai apporté", "as apporté", "a apporté", "a apporté", "avons apporté", "avez apporté", "ont apporté"],
        "imparfait": ["apportais", "apportais", "apportait", "apportait", "apportions", "apportiez", "apportaient"],
        "futur_simple": ["apporterai", "apporteras", "apportera", "apportera", "apporterons", "apporterez", "apporteront"],
        "conditionnel": ["apporterais", "apporterais", "apporterait", "apporterait", "apporterions", "apporteriez", "apporteraient"],
        "subjonctif": ["apporte", "apportes", "apporte", "apporte", "apportions", "apportiez", "apportent"]
    },
    "apprendre": {
        "translation": "to learn",
        "rank": 67,
        "irregular": True,
        "présent": ["apprends", "apprends", "apprend", "apprend", "apprenons", "apprenez", "apprennent"],
        "passé_composé": ["ai appris", "as appris", "a appris", "a appris", "avons appris", "avez appris", "ont appris"],
        "imparfait": ["apprenais", "apprenais", "apprenait", "apprenait", "apprenions", "appreniez", "apprenaient"],
        "futur_simple": ["apprendrai", "apprendras", "apprendra", "apprendra", "apprendrons", "apprendrez", "apprendront"],
        "conditionnel": ["apprendrais", "apprendrais", "apprendrait", "apprendrait", "apprendrions", "apprendriez", "apprendraient"],
        "subjonctif": ["apprenne", "apprennes", "apprenne", "apprenne", "apprenions", "appreniez", "apprennent"]
    },
    "changer": {
        "translation": "to change",
        "rank": 68,
        "irregular": False,
        "présent": ["change", "changes", "change", "change", "changeons", "changez", "changent"],
        "passé_composé": ["ai changé", "as changé", "a changé", "a changé", "avons changé", "avez changé", "ont changé"],
        "imparfait": ["changeais", "changeais", "changeait", "changeait", "changions", "changiez", "changeaient"],
        "futur_simple": ["changerai", "changeras", "changera", "changera", "changerons", "changerez", "changeront"],
        "conditionnel": ["changerais", "changerais", "changerait", "changerait", "changerions", "changeriez", "changeraient"],
        "subjonctif": ["change", "changes", "change", "change", "changions", "changiez", "changent"]
    },
    "choisir": {
        "translation": "to choose",
        "rank": 69,
        "irregular": False,
        "présent": ["choisis", "choisis", "choisit", "choisit", "choisissons", "choisissez", "choisissent"],
        "passé_composé": ["ai choisi", "as choisi", "a choisi", "a choisi", "avons choisi", "avez choisi", "ont choisi"],
        "imparfait": ["choisissais", "choisissais", "choisissait", "choisissait", "choisissions", "choisissiez", "choisissaient"],
        "futur_simple": ["choisirai", "choisiras", "choisira", "choisira", "choisirons", "choisirez", "choisiront"],
        "conditionnel": ["choisirais", "choisirais", "choisirait", "choisirait", "choisirions", "choisiriez", "choisiraient"],
        "subjonctif": ["choisisse", "choisisses", "choisisse", "choisisse", "choisissions", "choisissiez", "choisissent"]
    },
    "continuer": {
        "translation": "to continue",
        "rank": 70,
        "irregular": False,
        "présent": ["continue", "continues", "continue", "continue", "continuons", "continuez", "continuent"],
        "passé_composé": ["ai continué", "as continué", "a continué", "a continué", "avons continué", "avez continué", "ont continué"],
        "imparfait": ["continuais", "continuais", "continuait", "continuait", "continuions", "continuiez", "continuaient"],
        "futur_simple": ["continuerai", "continueras", "continuera", "continuera", "continuerons", "continuerez", "continueront"],
        "conditionnel": ["continuerais", "continuerais", "continuerait", "continuerait", "continuerions", "continueriez", "continueraient"],
        "subjonctif": ["continue", "continues", "continue", "continue", "continuions", "continuiez", "continuent"]
    },
    "courir": {
        "translation": "to run",
        "rank": 71,
        "irregular": True,
        "présent": ["cours", "cours", "court", "court", "courons", "courez", "courent"],
        "passé_composé": ["ai couru", "as couru", "a couru", "a couru", "avons couru", "avez couru", "ont couru"],
        "imparfait": ["courais", "courais", "courait", "courait", "courions", "couriez", "couraient"],
        "futur_simple": ["courrai", "courras", "courra", "courra", "courrons", "courrez", "courront"],
        "conditionnel": ["courrais", "courrais", "courrait", "courrait", "courrions", "courriez", "courraient"],
        "subjonctif": ["coure", "coures", "coure", "coure", "courions", "couriez", "courent"]
    },
    "décider": {
        "translation": "to decide",
        "rank": 72,
        "irregular": False,
        "présent": ["décide", "décides", "décide", "décide", "décidons", "décidez", "décident"],
        "passé_composé": ["ai décidé", "as décidé", "a décidé", "a décidé", "avons décidé", "avez décidé", "ont décidé"],
        "imparfait": ["décidais", "décidais", "décidait", "décidait", "décidions", "décidiez", "décidaient"],
        "futur_simple": ["déciderai", "décideras", "décidera", "décidera", "déciderons", "déciderez", "décideront"],
        "conditionnel": ["déciderais", "déciderais", "déciderait", "déciderait", "déciderions", "décideriez", "décideraient"],
        "subjonctif": ["décide", "décides", "décide", "décide", "décidions", "décidiez", "décident"]
    },
    "découvrir": {
        "translation": "to discover",
        "rank": 73,
        "irregular": True,
        "présent": ["découvre", "découvres", "découvre", "découvre", "découvrons", "découvrez", "découvrent"],
        "passé_composé": ["ai découvert", "as découvert", "a découvert", "a découvert", "avons découvert", "avez découvert", "ont découvert"],
        "imparfait": ["découvrais", "découvrais", "découvrait", "découvrait", "découvrions", "découvriez", "découvraient"],
        "futur_simple": ["découvrirai", "découvriras", "découvrira", "découvrira", "découvrirons", "découvrirez", "découvriront"],
        "conditionnel": ["découvrirais", "découvrirais", "découvrirait", "découvrirait", "découvririons", "découvririez", "découvriraient"],
        "subjonctif": ["découvre", "découvres", "découvre", "découvre", "découvrions", "découvriez", "découvrent"]
    },
    "descendre": {
        "translation": "to go down",
        "rank": 74,
        "irregular": False,
        "présent": ["descends", "descends", "descend", "descend", "descendons", "descendez", "descendent"],
        "passé_composé": ["suis descendu(e)", "es descendu(e)", "est descendu(e)", "est descendu(e)", "sommes descendu(e)s", "êtes descendu(e)(s)", "sont descendu(e)s"],
        "imparfait": ["descendais", "descendais", "descendait", "descendait", "descendions", "descendiez", "descendaient"],
        "futur_simple": ["descendrai", "descendras", "descendra", "descendra", "descendrons", "descendrez", "descendront"],
        "conditionnel": ["descendrais", "descendrais", "descendrait", "descendrait", "descendrions", "descendriez", "descendraient"],
        "subjonctif": ["descende", "descendes", "descende", "descende", "descendions", "descendiez", "descendent"]
    },
    "dormir": {
        "translation": "to sleep",
        "rank": 75,
        "irregular": True,
        "présent": ["dors", "dors", "dort", "dort", "dormons", "dormez", "dorment"],
        "passé_composé": ["ai dormi", "as dormi", "a dormi", "a dormi", "avons dormi", "avez dormi", "ont dormi"],
        "imparfait": ["dormais", "dormais", "dormait", "dormait", "dormions", "dormiez", "dormaient"],
        "futur_simple": ["dormirai", "dormiras", "dormira", "dormira", "dormirons", "dormirez", "dormiront"],
        "conditionnel": ["dormirais", "dormirais", "dormirait", "dormirait", "dormirions", "dormiriez", "dormiraient"],
        "subjonctif": ["dorme", "dormes", "dorme", "dorme", "dormions", "dormiez", "dorment"]
    },
    "écouter": {
        "translation": "to listen",
        "rank": 76,
        "irregular": False,
        "présent": ["écoute", "écoutes", "écoute", "écoute", "écoutons", "écoutez", "écoutent"],
        "passé_composé": ["ai écouté", "as écouté", "a écouté", "a écouté", "avons écouté", "avez écouté", "ont écouté"],
        "imparfait": ["écoutais", "écoutais", "écoutait", "écoutait", "écoutions", "écoutiez", "écoutaient"],
        "futur_simple": ["écouterai", "écouteras", "écoutera", "écoutera", "écouterons", "écouterez", "écouteront"],
        "conditionnel": ["écouterais", "écouterais", "écouterait", "écouterait", "écouterions", "écouteriez", "écouteraient"],
        "subjonctif": ["écoute", "écoutes", "écoute", "écoute", "écoutions", "écoutiez", "écoutent"]
    },
    "empêcher": {
        "translation": "to prevent",
        "rank": 77,
        "irregular": False,
        "présent": ["empêche", "empêches", "empêche", "empêche", "empêchons", "empêchez", "empêchent"],
        "passé_composé": ["ai empêché", "as empêché", "a empêché", "a empêché", "avons empêché", "avez empêché", "ont empêché"],
        "imparfait": ["empêchais", "empêchais", "empêchait", "empêchait", "empêchions", "empêchiez", "empêchaient"],
        "futur_simple": ["empêcherai", "empêcheras", "empêchera", "empêchera", "empêcherons", "empêcherez", "empêcheront"],
        "conditionnel": ["empêcherais", "empêcherais", "empêcherait", "empêcherait", "empêcherions", "empêcheriez", "empêcheraient"],
        "subjonctif": ["empêche", "empêches", "empêche", "empêche", "empêchions", "empêchiez", "empêchent"]
    },
    "enlever": {
        "translation": "to remove",
        "rank": 78,
        "irregular": False,
        "présent": ["enlève", "enlèves", "enlève", "enlève", "enlevons", "enlevez", "enlèvent"],
        "passé_composé": ["ai enlevé", "as enlevé", "a enlevé", "a enlevé", "avons enlevé", "avez enlevé", "ont enlevé"],
        "imparfait": ["enlevais", "enlevais", "enlevait", "enlevait", "enlevions", "enleviez", "enlevaient"],
        "futur_simple": ["enlèverai", "enlèveras", "enlèvera", "enlèvera", "enlèverons", "enlèverez", "enlèveront"],
        "conditionnel": ["enlèverais", "enlèverais", "enlèverait", "enlèverait", "enlèverions", "enlèveriez", "enlèveraient"],
        "subjonctif": ["enlève", "enlèves", "enlève", "enlève", "enlevions", "enleviez", "enlèvent"]
    },
    "espérer": {
        "translation": "to hope",
        "rank": 79,
        "irregular": False,
        "présent": ["espère", "espères", "espère", "espère", "espérons", "espérez", "espèrent"],
        "passé_composé": ["ai espéré", "as espéré", "a espéré", "a espéré", "avons espéré", "avez espéré", "ont espéré"],
        "imparfait": ["espérais", "espérais", "espérait", "espérait", "espérions", "espériez", "espéraient"],
        "futur_simple": ["espérerai", "espéreras", "espérera", "espérera", "espérerons", "espérerez", "espéreront"],
        "conditionnel": ["espérerais", "espérerais", "espérerait", "espérerait", "espérerions", "espéreriez", "espéreraient"],
        "subjonctif": ["espère", "espères", "espère", "espère", "espérions", "espériez", "espèrent"]
    },
    "essayer": {
        "translation": "to try",
        "rank": 80,
        "irregular": False,
        "présent": ["essaie", "essaies", "essaie", "essaie", "essayons", "essayez", "essaient"],
        "passé_composé": ["ai essayé", "as essayé", "a essayé", "a essayé", "avons essayé", "avez essayé", "ont essayé"],
        "imparfait": ["essayais", "essayais", "essayait", "essayait", "essayions", "essayiez", "essayaient"],
        "futur_simple": ["essaierai", "essaieras", "essaiera", "essaiera", "essaierons", "essaierez", "essaieront"],
        "conditionnel": ["essaierais", "essaierais", "essaierait", "essaierait", "essaierions", "essaieriez", "essaieraient"],
        "subjonctif": ["essaie", "essaies", "essaie", "essaie", "essayions", "essayiez", "essaient"]
    },
    "expliquer": {
        "translation": "to explain",
        "rank": 81,
        "irregular": False,
        "présent": ["explique", "expliques", "explique", "explique", "expliquons", "expliquez", "expliquent"],
        "passé_composé": ["ai expliqué", "as expliqué", "a expliqué", "a expliqué", "avons expliqué", "avez expliqué", "ont expliqué"],
        "imparfait": ["expliquais", "expliquais", "expliquait", "expliquait", "expliquions", "expliquiez", "expliquaient"],
        "futur_simple": ["expliquerai", "expliqueras", "expliquera", "expliquera", "expliquerons", "expliquerez", "expliqueront"],
        "conditionnel": ["expliquerais", "expliquerais", "expliquerait", "expliquerait", "expliquerions", "expliqueriez", "expliqueraient"],
        "subjonctif": ["explique", "expliques", "explique", "explique", "expliquions", "expliquiez", "expliquent"]
    },
    "gagner": {
        "translation": "to win/earn",
        "rank": 82,
        "irregular": False,
        "présent": ["gagne", "gagnes", "gagne", "gagne", "gagnons", "gagnez", "gagnent"],
        "passé_composé": ["ai gagné", "as gagné", "a gagné", "a gagné", "avons gagné", "avez gagné", "ont gagné"],
        "imparfait": ["gagnais", "gagnais", "gagnait", "gagnait", "gagnions", "gagniez", "gagnaient"],
        "futur_simple": ["gagnerai", "gagneras", "gagnera", "gagnera", "gagnerons", "gagnerez", "gagneront"],
        "conditionnel": ["gagnerais", "gagnerais", "gagnerait", "gagnerait", "gagnerions", "gagneriez", "gagneraient"],
        "subjonctif": ["gagne", "gagnes", "gagne", "gagne", "gagnions", "gagniez", "gagnent"]
    },
    "garder": {
        "translation": "to keep",
        "rank": 83,
        "irregular": False,
        "présent": ["garde", "gardes", "garde", "garde", "gardons", "gardez", "gardent"],
        "passé_composé": ["ai gardé", "as gardé", "a gardé", "a gardé", "avons gardé", "avez gardé", "ont gardé"],
        "imparfait": ["gardais", "gardais", "gardait", "gardait", "gardions", "gardiez", "gardaient"],
        "futur_simple": ["garderai", "garderas", "gardera", "gardera", "garderons", "garderez", "garderont"],
        "conditionnel": ["garderais", "garderais", "garderait", "garderait", "garderions", "garderiez", "garderaient"],
        "subjonctif": ["garde", "gardes", "garde", "garde", "gardions", "gardiez", "gardent"]
    },
    "jouer": {
        "translation": "to play",
        "rank": 84,
        "irregular": False,
        "présent": ["joue", "joues", "joue", "joue", "jouons", "jouez", "jouent"],
        "passé_composé": ["ai joué", "as joué", "a joué", "a joué", "avons joué", "avez joué", "ont joué"],
        "imparfait": ["jouais", "jouais", "jouait", "jouait", "jouions", "jouiez", "jouaient"],
        "futur_simple": ["jouerai", "joueras", "jouera", "jouera", "jouerons", "jouerez", "joueront"],
        "conditionnel": ["jouerais", "jouerais", "jouerait", "jouerait", "jouerions", "joueriez", "joueraient"],
        "subjonctif": ["joue", "joues", "joue", "joue", "jouions", "jouiez", "jouent"]
    },
    "manger": {
        "translation": "to eat",
        "rank": 85,
        "irregular": False,
        "présent": ["mange", "manges", "mange", "mange", "mangeons", "mangez", "mangent"],
        "passé_composé": ["ai mangé", "as mangé", "a mangé", "a mangé", "avons mangé", "avez mangé", "ont mangé"],
        "imparfait": ["mangeais", "mangeais", "mangeait", "mangeait", "mangions", "mangiez", "mangeaient"],
        "futur_simple": ["mangerai", "mangeras", "mangera", "mangera", "mangerons", "mangerez", "mangeront"],
        "conditionnel": ["mangerais", "mangerais", "mangerait", "mangerait", "mangerions", "mangeriez", "mangeraient"],
        "subjonctif": ["mange", "manges", "mange", "mange", "mangions", "mangiez", "mangent"]
    },
    "oublier": {
        "translation": "to forget",
        "rank": 86,
        "irregular": False,
        "présent": ["oublie", "oublies", "oublie", "oublie", "oublions", "oubliez", "oublient"],
        "passé_composé": ["ai oublié", "as oublié", "a oublié", "a oublié", "avons oublié", "avez oublié", "ont oublié"],
        "imparfait": ["oubliais", "oubliais", "oubliait", "oubliait", "oubliions", "oubliiez", "oubliaient"],
        "futur_simple": ["oublierai", "oublieras", "oubliera", "oubliera", "oublierons", "oublierez", "oublieront"],
        "conditionnel": ["oublierais", "oublierais", "oublierait", "oublierait", "oublierions", "oublieriez", "oublieraient"],
        "subjonctif": ["oublie", "oublies", "oublie", "oublie", "oubliions", "oubliiez", "oublient"]
    },
    "partager": {
        "translation": "to share",
        "rank": 87,
        "irregular": False,
        "présent": ["partage", "partages", "partage", "partage", "partageons", "partagez", "partagent"],
        "passé_composé": ["ai partagé", "as partagé", "a partagé", "a partagé", "avons partagé", "avez partagé", "ont partagé"],
        "imparfait": ["partageais", "partageais", "partageait", "partageait", "partagions", "partagiez", "partageaient"],
        "futur_simple": ["partagerai", "partageras", "partagera", "partagera", "partagerons", "partagerez", "partageront"],
        "conditionnel": ["partagerais", "partagerais", "partagerait", "partagerait", "partagerions", "partageriez", "partageraient"],
        "subjonctif": ["partage", "partages", "partage", "partage", "partagions", "partagiez", "partagent"]
    },
    "payer": {
        "translation": "to pay",
        "rank": 88,
        "irregular": False,
        "présent": ["paie", "paies", "paie", "paie", "payons", "payez", "paient"],
        "passé_composé": ["ai payé", "as payé", "a payé", "a payé", "avons payé", "avez payé", "ont payé"],
        "imparfait": ["payais", "payais", "payait", "payait", "payions", "payiez", "payaient"],
        "futur_simple": ["paierai", "paieras", "paiera", "paiera", "paierons", "paierez", "paieront"],
        "conditionnel": ["paierais", "paierais", "paierait", "paierait", "paierions", "paieriez", "paieraient"],
        "subjonctif": ["paie", "paies", "paie", "paie", "payions", "payiez", "paient"]
    },
    "travailler": {
        "translation": "to work",
        "rank": 89,
        "irregular": False,
        "présent": ["travaille", "travailles", "travaille", "travaille", "travaillons", "travaillez", "travaillent"],
        "passé_composé": ["ai travaillé", "as travaillé", "a travaillé", "a travaillé", "avons travaillé", "avez travaillé", "ont travaillé"],
        "imparfait": ["travaillais", "travaillais", "travaillait", "travaillait", "travaillions", "travailliez", "travaillaient"],
        "futur_simple": ["travaillerai", "travailleras", "travaillera", "travaillera", "travaillerons", "travaillerez", "travailleront"],
        "conditionnel": ["travaillerais", "travaillerais", "travaillerait", "travaillerait", "travaillerions", "travailleriez", "travailleraient"],
        "subjonctif": ["travaille", "travailles", "travaille", "travaille", "travaillions", "travailliez", "travaillent"]
    },
    "tomber": {
        "translation": "to fall",
        "rank": 90,
        "irregular": False,
        "présent": ["tombe", "tombes", "tombe", "tombe", "tombons", "tombez", "tombent"],
        "passé_composé": ["suis tombé(e)", "es tombé(e)", "est tombé(e)", "est tombé(e)", "sommes tombé(e)s", "êtes tombé(e)(s)", "sont tombé(e)s"],
        "imparfait": ["tombais", "tombais", "tombait", "tombait", "tombions", "tombiez", "tombaient"],
        "futur_simple": ["tomberai", "tomberas", "tombera", "tombera", "tomberons", "tomberez", "tomberont"],
        "conditionnel": ["tomberais", "tomberais", "tomberait", "tomberait", "tomberions", "tomberiez", "tomberaient"],
        "subjonctif": ["tombe", "tombes", "tombe", "tombe", "tombions", "tombiez", "tombent"]
    },
    "rentrer": {
        "translation": "to return home",
        "rank": 91,
        "irregular": False,
        "présent": ["rentre", "rentres", "rentre", "rentre", "rentrons", "rentrez", "rentrent"],
        "passé_composé": ["suis rentré(e)", "es rentré(e)", "est rentré(e)", "est rentré(e)", "sommes rentré(e)s", "êtes rentré(e)(s)", "sont rentré(e)s"],
        "imparfait": ["rentrais", "rentrais", "rentrait", "rentrait", "rentrions", "rentriez", "rentraient"],
        "futur_simple": ["rentrerai", "rentreras", "rentrera", "rentrera", "rentrerons", "rentrerez", "rentreront"],
        "conditionnel": ["rentrerais", "rentrerais", "rentrerait", "rentrerait", "rentrerions", "rentreriez", "rentreraient"],
        "subjonctif": ["rentre", "rentres", "rentre", "rentre", "rentrions", "rentriez", "rentrent"]
    },
    "manquer": {
        "translation": "to miss",
        "rank": 92,
        "irregular": False,
        "présent": ["manque", "manques", "manque", "manque", "manquons", "manquez", "manquent"],
        "passé_composé": ["ai manqué", "as manqué", "a manqué", "a manqué", "avons manqué", "avez manqué", "ont manqué"],
        "imparfait": ["manquais", "manquais", "manquait", "manquait", "manquions", "manquiez", "manquaient"],
        "futur_simple": ["manquerai", "manqueras", "manquera", "manquera", "manquerons", "manquerez", "manqueront"],
        "conditionnel": ["manquerais", "manquerais", "manquerait", "manquerait", "manquerions", "manqueriez", "manqueraient"],
        "subjonctif": ["manque", "manques", "manque", "manque", "manquions", "manquiez", "manquent"]
    },
    "poser": {
        "translation": "to put/ask",
        "rank": 93,
        "irregular": False,
        "présent": ["pose", "poses", "pose", "pose", "posons", "posez", "posent"],
        "passé_composé": ["ai posé", "as posé", "a posé", "a posé", "avons posé", "avez posé", "ont posé"],
        "imparfait": ["posais", "posais", "posait", "posait", "posions", "posiez", "posaient"],
        "futur_simple": ["poserai", "poseras", "posera", "posera", "poserons", "poserez", "poseront"],
        "conditionnel": ["poserais", "poserais", "poserait", "poserait", "poserions", "poseriez", "poseraient"],
        "subjonctif": ["pose", "poses", "pose", "pose", "posions", "posiez", "posent"]
    },
    "se souvenir": {
        "translation": "to remember",
        "rank": 94,
        "irregular": True,
        "présent": ["me souviens", "te souviens", "se souvient", "se souvient", "nous souvenons", "vous souvenez", "se souviennent"],
        "passé_composé": ["me suis souvenu(e)", "t'es souvenu(e)", "s'est souvenu(e)", "s'est souvenu(e)", "nous sommes souvenu(e)s", "vous êtes souvenu(e)(s)", "se sont souvenu(e)s"],
        "imparfait": ["me souvenais", "te souvenais", "se souvenait", "se souvenait", "nous souvenions", "vous souveniez", "se souvenaient"],
        "futur_simple": ["me souviendrai", "te souviendras", "se souviendra", "se souviendra", "nous souviendrons", "vous souviendrez", "se souviendront"],
        "conditionnel": ["me souviendrais", "te souviendrais", "se souviendrait", "se souviendrait", "nous souviendrions", "vous souviendriez", "se souviendraient"],
        "subjonctif": ["me souvienne", "te souviennes", "se souvienne", "se souvienne", "nous souvenions", "vous souveniez", "se souviennent"]
    },
    "fermer": {
        "translation": "to close",
        "rank": 95,
        "irregular": False,
        "présent": ["ferme", "fermes", "ferme", "ferme", "fermons", "fermez", "ferment"],
        "passé_composé": ["ai fermé", "as fermé", "a fermé", "a fermé", "avons fermé", "avez fermé", "ont fermé"],
        "imparfait": ["fermais", "fermais", "fermait", "fermait", "fermions", "fermiez", "fermaient"],
        "futur_simple": ["fermerai", "fermeras", "fermera", "fermera", "fermerons", "fermerez", "fermeront"],
        "conditionnel": ["fermerais", "fermerais", "fermerait", "fermerait", "fermerions", "fermeriez", "fermeraient"],
        "subjonctif": ["ferme", "fermes", "ferme", "ferme", "fermions", "fermiez", "ferment"]
    },
    "réussir": {
        "translation": "to succeed",
        "rank": 96,
        "irregular": False,
        "présent": ["réussis", "réussis", "réussit", "réussit", "réussissons", "réussissez", "réussissent"],
        "passé_composé": ["ai réussi", "as réussi", "a réussi", "a réussi", "avons réussi", "avez réussi", "ont réussi"],
        "imparfait": ["réussissais", "réussissais", "réussissait", "réussissait", "réussissions", "réussissiez", "réussissaient"],
        "futur_simple": ["réussirai", "réussiras", "réussira", "réussira", "réussirons", "réussirez", "réussiront"],
        "conditionnel": ["réussirais", "réussirais", "réussirait", "réussirait", "réussirions", "réussiriez", "réussiraient"],
        "subjonctif": ["réussisse", "réussisses", "réussisse", "réussisse", "réussissions", "réussissiez", "réussissent"]
    },
    "utiliser": {
        "translation": "to use",
        "rank": 97,
        "irregular": False,
        "présent": ["utilise", "utilises", "utilise", "utilise", "utilisons", "utilisez", "utilisent"],
        "passé_composé": ["ai utilisé", "as utilisé", "a utilisé", "a utilisé", "avons utilisé", "avez utilisé", "ont utilisé"],
        "imparfait": ["utilisais", "utilisais", "utilisait", "utilisait", "utilisions", "utilisiez", "utilisaient"],
        "futur_simple": ["utiliserai", "utiliseras", "utilisera", "utilisera", "utiliserons", "utiliserez", "utiliseront"],
        "conditionnel": ["utiliserais", "utiliserais", "utiliserait", "utiliserait", "utiliserions", "utiliseriez", "utiliseraient"],
        "subjonctif": ["utilise", "utilises", "utilise", "utilise", "utilisions", "utilisiez", "utilisent"]
    },
    "couper": {
        "translation": "to cut",
        "rank": 98,
        "irregular": False,
        "présent": ["coupe", "coupes", "coupe", "coupe", "coupons", "coupez", "coupent"],
        "passé_composé": ["ai coupé", "as coupé", "a coupé", "a coupé", "avons coupé", "avez coupé", "ont coupé"],
        "imparfait": ["coupais", "coupais", "coupait", "coupait", "coupions", "coupiez", "coupaient"],
        "futur_simple": ["couperai", "couperas", "coupera", "coupera", "couperons", "couperez", "couperont"],
        "conditionnel": ["couperais", "couperais", "couperait", "couperait", "couperions", "couperiez", "couperaient"],
        "subjonctif": ["coupe", "coupes", "coupe", "coupe", "coupions", "coupiez", "coupent"]
    },
    "rencontrer": {
        "translation": "to meet",
        "rank": 99,
        "irregular": False,
        "présent": ["rencontre", "rencontres", "rencontre", "rencontre", "rencontrons", "rencontrez", "rencontrent"],
        "passé_composé": ["ai rencontré", "as rencontré", "a rencontré", "a rencontré", "avons rencontré", "avez rencontré", "ont rencontré"],
        "imparfait": ["rencontrais", "rencontrais", "rencontrait", "rencontrait", "rencontrions", "rencontriez", "rencontraient"],
        "futur_simple": ["rencontrerai", "rencontreras", "rencontrera", "rencontrera", "rencontrerons", "rencontrerez", "rencontreront"],
        "conditionnel": ["rencontrerais", "rencontrerais", "rencontrerait", "rencontrerait", "rencontrerions", "rencontreriez", "rencontreraient"],
        "subjonctif": ["rencontre", "rencontres", "rencontre", "rencontre", "rencontrions", "rencontriez", "rencontrent"]
    }
}
